apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://${KUBE_SERVER}
  name: current-cluster 
users:
- name: jenkins
  user:
    token: ${SERVICE_ACCOUNT_TOKEN}
contexts:
- context:
  name: default-context
  context:
    cluster: current-cluster
    user: jenkins
current-context: default-context

